version: '3.0'

services:
  tileserver-gl:
    build:
      context: tileserver-gl/tileserver-gl
    volumes:
      - ./tileserver-gl:/data
      - ./tileserver-gl/static/public/index.html:/usr/src/app/public/templates/index.tmpl
      - ./tileserver-gl/static/public:/usr/src/app/public/resources
    networks:
      - openmaptiles-conn

  nginx:
    build:
      context: nginx
    depends_on:
      - tileserver-gl
    environment:
      - NGINX_DISABLE_CACHE
    volumes:
      - ./nginx/nginx.template.conf:/etc/nginx/nginx.template.conf:ro
      - nginx-cache:/cache
      - ./openmaptiles/data/expire_tiles:/data/expire_tiles
    networks:
      - openmaptiles-conn
    ports:
      - "${NGINX_PORT:-8080}:80"
      - "127.0.0.1:8082:82"

networks:
  openmaptiles-conn:
    name: openmaptiles-postgres-conn
    driver: bridge

volumes:
  nginx-cache:
