openmaptiles_v3:
  public: true
  formats: [pbf]
  uri: tmsource:///data/openmaptiles.tm2source
  overrideInfo:
    attribution: 'Map data © <a href="http://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    Layer:
    _prefs:
    tiles: {var: OPENMAPTILES_V3_TILES_URLS}

# Raster

openmaptiles_v3_raster:
  public: true
  formats: [pbf]
  uri: tmsource:///data/openmaptiles.tm2source
  overrideInfo:
    attribution: 'Map data © <a href="http://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    Layer:
    _prefs:
    tiles: {var: OPENMAPTILES_V3_TILES_URLS_INTERNAL} # Duplicate source config to change this URL

bright:
  public: true
  formats: [png, jpeg, webp]
  uri: kartotherian+gl:///
  params:
    style: bright
  overrideInfo:
    tiles: {var: BRIGHT_TILES_URLS}
